import 'package:flutter/material.dart';
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: prefer_single_quotes

//This file is automatically generated. DO NOT EDIT, all your changes would be lost.

class labels {
  const labels();

  static labels of(BuildContext context) =>
      Localizations.of<labels>(context, WidgetsLocalizations);

  @override
  TextDirection get textDirection => TextDirection.ltr;

  String get add => "Add";

  String get appTitle => "Daly Budget";

  String get beginNewCycle => "Begin new cycle";

  String get budget => "Budget";

  String get cancel => "Cancel";

  String get changeBudget => "Change budget";

  String get changeCurrency => "Change currency";

  String get chooseCurrency => "Choose currency";

  String get confirm => "Confirm";

  String get currencyEUR => "EUR (€)";

  String get currencyGBP => "GBP (£)";


  String get history => "History";

  String get leftToSpend => "Left to spend";

  String get newExpense => "New expense";

  String get startingBudget => "Starting budget";

  String get sumOfExpenses => "Sum of expenses";
}